name: Update Traffic Stats
on:
  schedule:
    - cron: '0 0 * * *' # Raz dziennie o północy
  workflow_dispatch: # Pozwala odpalić ręcznie

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Data
        run: |
          curl -H "Authorization: token ${{ secrets.METRICS_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/traffic/views \
          > data.json
      - name: Commit changes
        run: |
          git config --global user.name 'Stats Bot'
          git config --global user.email 'bot@github.com'
          git add data.json
          git commit -m "Automated data update" || exit 0
          git push
